import { LearningModule } from "./module-types";

export const articleModules: LearningModule[] = [
  {
    id: 1,
    slug: "dasar-dasar-penganggaran",
    title: "Dasar-Dasar Penganggaran: Kendalikan Uang Anda",
    description:
      "Pelajari fundamental membuat dan memelihara anggaran yang sesuai dengan gaya hidup Anda.",
    category: "budgeting",
    duration: "15 menit",
    students: 15420,
    level: "Pemula",
    type: "article",
  image: "/illustrations/dasar-dasar-penganggaran.svg",
    content: [
      {
        title: "Apa itu Anggaran?",
        text: "Anggaran adalah rencana keuangan yang membantu Anda mengalokasikan pendapatan untuk berbagai kebutuhan dan tujuan. Dengan anggaran yang baik, Anda dapat mengontrol pengeluaran dan mencapai tujuan finansial.\n\nAnggaran bukan hanya tentang membatasi pengeluaran, tetapi juga tentang memberikan kebebasan finansial. Ketika Anda tahu persis kemana uang Anda pergi, Anda dapat membuat keputusan yang lebih bijak dan menghindari stres keuangan.\n\nSebuah anggaran yang efektif harus realistis, fleksibel, dan dapat disesuaikan dengan perubahan situasi keuangan Anda. Ingatlah bahwa anggaran adalah alat untuk mencapai tujuan, bukan penghalang untuk menikmati hidup.",
      },
      {
        title: "Langkah Membuat Anggaran",
        text: "1. Hitung total pendapatan bulanan dari semua sumber\n2. Catat semua pengeluaran tetap (sewa, listrik, asuransi, cicilan)\n3. Identifikasi pengeluaran variabel (makanan, transportasi, hiburan)\n4. Tentukan alokasi untuk kebutuhan, keinginan, dan tabungan\n5. Sisihkan untuk dana darurat dan investasi\n6. Monitor dan evaluasi setiap bulan\n\nTips penting: Mulai dengan mencatat semua pengeluaran selama sebulan untuk mendapatkan gambaran yang akurat. Gunakan aplikasi atau spreadsheet untuk memudahkan tracking. Jangan lupa untuk menyisakan ruang untuk pengeluaran tak terduga.",
      },
      {
        title: "Tips Mengelola Anggaran",
        text: "Gunakan aturan 50/30/20: 50% untuk kebutuhan pokok, 30% untuk keinginan, 20% untuk tabungan dan investasi. Aturan ini memberikan keseimbangan antara memenuhi kebutuhan, menikmati hidup, dan mempersiapkan masa depan.\n\nSelalu catat pengeluaran harian dan review anggaran setiap minggu. Buat kategori pengeluaran yang spesifik agar lebih mudah dianalisis. Jika ada kategori yang sering over budget, evaluasi apakah alokasi perlu disesuaikan atau pengeluaran perlu dikurangi.\n\nJangan terlalu ketat pada diri sendiri. Sisakan sedikit ruang untuk 'fun money' agar anggaran tetap sustainable dalam jangka panjang.",
      },
      {
        title: "Mengatasi Tantangan Anggaran",
        text: "Tantangan umum dalam penganggaran adalah pengeluaran impulsif dan kurangnya disiplin. Untuk mengatasinya, terapkan aturan 24 jam sebelum membeli barang non-esensial yang mahal.\n\nBuat sistem reward untuk diri sendiri ketika berhasil mengikuti anggaran. Misalnya, jika berhasil hemat 10% dari target bulanan, gunakan sebagian untuk membeli sesuatu yang diinginkan.\n\nJangan menyerah jika gagal di bulan pertama. Anggaran adalah skill yang perlu dipraktikkan. Sesuaikan dan perbaiki terus hingga menemukan formula yang cocok untuk gaya hidup Anda.",
      },
      {
        title: "Studi Kasus Penerapan Anggaran",
        text: "Rina dengan pendapatan Rp8 juta selalu habis tiap bulan. Setelah 2 bulan mencatat pengeluaran, ia menemukan 22% pengeluaran bocor pada makanan online & impulse shopping. Dengan envelope digital dan batas mingguan, ia memangkas bocor menjadi 8% dan mengalihkan selisih ke dana darurat. Dalam 6 bulan ia menabung Rp4,5 juta tanpa merasa 'tersiksa'.",
      },
      {
        title: "Rencana Aksi 30 Hari",
        text: "Hari 1-7: Catat semua pengeluaran (tanpa ubah perilaku).\nHari 8-14: Kelompokkan & tandai kategori boros (>15% di luar kebutuhan).\nHari 15-21: Terapkan batas mingguan & aturan 24 jam.\nHari 22-30: Review, adjust kategori, set auto-transfer tabungan di H+1 gajian.\n\nUlangi siklus per bulan untuk continuous improvement.",
      },
    ],
    quiz: [
      {
        question:
          "Berapa persen dari pendapatan yang sebaiknya dialokasikan untuk tabungan menurut aturan 50/30/20?",
        options: ["10%", "15%", "20%", "25%"],
        correct: 2,
      },
      {
        question: "Apa yang termasuk dalam pengeluaran tetap?",
        options: [
          "Makanan dan hiburan",
          "Sewa dan cicilan",
          "Belanja dan jalan-jalan",
          "Hadiah dan donasi",
        ],
        correct: 1,
      },
      {
        question: "Mengapa anggaran perlu di-review secara berkala?",
        options: [
          "Untuk menambah pengeluaran",
          "Untuk menyesuaikan dengan perubahan situasi",
          "Untuk mengurangi tabungan",
          "Untuk menghilangkan kategori pengeluaran",
        ],
        correct: 1,
      },
      {
        question: "Apa tujuan utama dari membuat anggaran?",
        options: [
          "Membatasi semua pengeluaran",
          "Mengontrol keuangan dan mencapai tujuan finansial",
          "Menghindari berbelanja",
          "Menyimpan semua uang",
        ],
        correct: 1,
      },
      {
        question:
          "Strategi apa yang bisa diterapkan untuk mengatasi pengeluaran impulsif?",
        options: [
          "Membawa uang cash lebih banyak",
          "Menerapkan aturan 24 jam sebelum membeli",
          "Berbelanja setiap hari",
          "Tidak membuat daftar belanja",
        ],
        correct: 1,
      },
    ],
  },
  {
    id: 2,
    slug: "fundamental-investasi",
    title: "Fundamental Investasi: Membangun Kekayaan",
    description:
      "Temukan dasar-dasar investasi, dari saham dan obligasi hingga strategi diversifikasi.",
    category: "investing",
    duration: "20 menit",
    students: 12350,
    level: "Pemula",
    type: "article",
  image: "/illustrations/fundamental-investasi.svg",
    content: [
      {
        title: "Mengapa Harus Investasi?",
        text: "Investasi adalah cara untuk mengalahkan inflasi dan membangun kekayaan jangka panjang. Dengan menyimpan uang di bank saja, nilai uang Anda akan tergerus inflasi setiap tahunnya.\n\nInflasi rata-rata di Indonesia sekitar 3-4% per tahun, sementara bunga tabungan hanya 1-2%. Artinya, daya beli uang Anda berkurang 1-2% setiap tahun jika hanya menabung.\n\nInvestasi memberikan potensi return yang lebih tinggi dari inflasi, sehingga nilai riil uang Anda dapat bertumbuh. Semakin dini Anda mulai berinvestasi, semakin besar manfaat compound interest yang akan Anda dapatkan.",
      },
      {
        title: "Jenis-Jenis Investasi",
        text: "1. Saham - kepemilikan perusahaan dengan potensi return tinggi tapi risiko tinggi\n2. Obligasi - surat utang dengan return stabil dan risiko rendah\n3. Reksa Dana - investasi kolektif yang dikelola manajer investasi profesional\n4. Emas - investasi safe haven yang tahan inflasi\n5. Properti - investasi aset riil dengan potensi capital gain dan rental yield\n6. Deposito - investasi dengan return tetap dan risiko minimal\n\nSetiap jenis investasi memiliki karakteristik risiko dan return yang berbeda. Pemula sebaiknya mulai dari reksa dana atau saham blue chip yang relatif stabil.",
      },
      {
        title: "Prinsip Diversifikasi",
        text: "Jangan taruh semua telur dalam satu keranjang. Diversifikasi membantu mengurangi risiko dengan menyebar investasi ke berbagai instrumen, sektor, dan geografis yang berbeda.\n\nDiversifikasi bisa dilakukan secara horizontal (berbagai jenis aset) dan vertikal (berbagai perusahaan dalam satu sektor). Misalnya, kombinasi saham, obligasi, dan emas dengan proporsi yang sesuai profil risiko.\n\nUntuk pemula, reksa dana campuran sudah memberikan diversifikasi otomatis. Seiring bertambahnya pengetahuan dan modal, Anda bisa melakukan diversifikasi mandiri.",
      },
      {
        title: "Strategi Investasi Jangka Panjang",
        text: "Dollar Cost Averaging (DCA) adalah strategi investasi rutin dengan nominal tetap, terlepas dari kondisi pasar. Strategi ini membantu mengurangi risiko timing dan volatilitas pasar.\n\nFokus pada fundamental perusahaan atau aset yang Anda beli, bukan fluktuasi harga jangka pendek. Investasi terbaik adalah yang Anda pahami dan percayai untuk jangka panjang.\n\nRebalancing portofolio secara berkala untuk memastikan alokasi aset tetap sesuai target. Jual yang sudah overweight, beli yang underweight.",
      },
      {
        title: "Studi Kasus Portofolio Diversifikasi",
        text: "Portofolio A hanya saham teknologi anjlok -25% saat koreksi. Portofolio B (60% saham, 25% obligasi, 10% emas, 5% kas) hanya turun -8% dan pulih dalam 3 bulan. Diversifikasi menurunkan volatilitas & mempercepat recovery mental investor.",
      },
      {
        title: "Checklist Investor Pemula",
        text: "1. Dana darurat ≥ 3-6 bulan.\n2. Utang konsumtif terkontrol (DSR <30%).\n3. Alokasi aset ditulis jelas.\n4. Paham risiko tiap instrumen.\n5. Rencana exit (jual) & rebalancing tertulis.\n6. Tidak gunakan dana kebutuhan <3 tahun.\n7. Konsisten DCA minimal 12 bulan.",
      },
    ],
    quiz: [
      {
        question: "Apa tujuan utama dari diversifikasi investasi?",
        options: [
          "Meningkatkan return",
          "Mengurangi risiko",
          "Mempercepat keuntungan",
          "Menghindari pajak",
        ],
        correct: 1,
      },
      {
        question: "Mengapa investasi penting untuk mengalahkan inflasi?",
        options: [
          "Karena inflasi selalu naik",
          "Karena return investasi umumnya lebih tinggi dari inflasi",
          "Karena uang akan habis",
          "Karena bank tidak aman",
        ],
        correct: 1,
      },
      {
        question: "Apa itu Dollar Cost Averaging (DCA)?",
        options: [
          "Investasi sekali dalam jumlah besar",
          "Investasi rutin dengan nominal tetap",
          "Investasi hanya saat harga turun",
          "Investasi hanya di saham Amerika",
        ],
        correct: 1,
      },
      {
        question: "Instrumen investasi mana yang paling cocok untuk pemula?",
        options: ["Saham individual", "Reksa dana", "Forex", "Cryptocurrency"],
        correct: 1,
      },
      {
        question: "Kapan sebaiknya melakukan rebalancing portofolio?",
        options: [
          "Setiap hari",
          "Secara berkala sesuai rencana",
          "Hanya saat rugi",
          "Tidak pernah",
        ],
        correct: 1,
      },
    ],
  },
  {
    id: 3,
    slug: "strategi-dana-darurat",
    title: "Strategi Dana Darurat",
    description:
      "Bangun jaring pengaman keuangan yang solid dengan strategi dana darurat yang terbukti.",
    category: "planning",
    duration: "12 menit",
    students: 9870,
    level: "Pemula",
    type: "article",
  image: "/illustrations/strategi-dana-darurat.svg",
    content: [
      {
        title: "Pentingnya Dana Darurat",
        text: "Dana darurat adalah uang yang disisihkan khusus untuk menghadapi situasi tak terduga seperti kehilangan pekerjaan, sakit, atau kerusakan kendaraan. Ini adalah fondasi keuangan yang harus dimiliki sebelum berinvestasi.\n\nTanpa dana darurat, Anda akan terpaksa menggunakan kartu kredit, meminjam uang, atau menjual investasi saat kondisi tidak menguntungkan ketika menghadapi keadaan darurat.\n\nDana darurat memberikan ketenangan pikiran dan fleksibilitas dalam mengambil keputusan finansial. Anda tidak akan terjebak dalam situasi yang memaksa Anda mengambil keputusan buruk karena tekanan keuangan.",
      },
      {
        title: "Berapa Besar Dana Darurat?",
        text: "Idealnya 6-12 bulan pengeluaran bulanan. Untuk karyawan tetap minimal 6 bulan, untuk freelancer atau wirausaha sebaiknya 12 bulan karena pendapatan yang tidak pasti.\n\nMulai dengan target 1 bulan pengeluaran, lalu tingkatkan bertahap hingga mencapai target ideal. Jangan terbebani dengan target besar di awal, yang penting konsisten menyisihkan dana.\n\nHitung berdasarkan pengeluaran bulanan, bukan pendapatan. Misalnya jika pengeluaran bulanan Rp 5 juta, maka dana darurat minimal Rp 30 juta (6 bulan).",
      },
      {
        title: "Dimana Menyimpan Dana Darurat?",
        text: "Simpan di instrumen yang mudah dicairkan (liquid) seperti tabungan biasa, deposito jangka pendek, atau reksa dana pasar uang. Prioritas utama adalah likuiditas, bukan return.\n\nHindari investasi berisiko tinggi seperti saham atau crypto untuk dana darurat. Dana darurat harus stabil nilainya dan bisa diakses kapan saja tanpa penalty.\n\nPertimbangkan untuk membagi dana darurat ke beberapa tempat: sebagian di tabungan untuk akses cepat, sebagian di deposito untuk return lebih baik.",
      },
      {
        title: "Strategi Membangun Dana Darurat",
        text: "Otomatisasi adalah kunci sukses. Set up auto debit dari rekening utama ke rekening khusus dana darurat setiap gajian. Treat it like a bill yang harus dibayar.\n\nMulai dari yang kecil tapi konsisten. Lebih baik Rp 500 ribu per bulan secara konsisten daripada Rp 2 juta sekali lalu berhenti.\n\nGunakan windfall seperti bonus, THR, atau uang lembur untuk mempercepat pembentukan dana darurat. Jangan gunakan untuk lifestyle inflation.",
      },
      {
        title: "Kesalahan Umum Dana Darurat",
        text: "1. Disatukan dengan akun transaksi harian sehingga mudah terpakai.\n2. Ditaruh di instrumen tinggi risiko.\n3. Tidak di-adjust saat pengeluaran naik.\n4. Berhenti menabung setelah 1-2 bulan.\nDengan menghindari kesalahan ini akumulasi lebih cepat dan terproteksi.",
      },
      {
        title: "Rencana Aksi 90 Hari",
        text: "Bulan 1: Hitung rata-rata pengeluaran & buka akun terpisah.\nBulan 2: Auto transfer 10-15% income ke akun dana darurat.\nBulan 3: Tambah sumber (jualan barang tidak terpakai, freelance kecil). Evaluasi progres vs target 6 bulan. Ulangi siklus hingga tercapai.",
      },
    ],
    quiz: [
      {
        question:
          "Berapa bulan pengeluaran yang ideal untuk dana darurat seorang karyawan tetap?",
        options: ["3-4 bulan", "6-12 bulan", "12-24 bulan", "1-2 bulan"],
        correct: 1,
      },
      {
        question: "Dimana sebaiknya menyimpan dana darurat?",
        options: ["Saham", "Tabungan atau deposito", "Cryptocurrency", "Emas"],
        correct: 1,
      },
      {
        question:
          "Apa prioritas utama dalam memilih instrumen untuk dana darurat?",
        options: [
          "Return tinggi",
          "Likuiditas tinggi",
          "Risiko tinggi",
          "Jangka waktu panjang",
        ],
        correct: 1,
      },
      {
        question: "Kapan sebaiknya mulai membangun dana darurat?",
        options: [
          "Setelah investasi",
          "Sebelum investasi",
          "Bersamaan dengan investasi",
          "Tidak perlu",
        ],
        correct: 1,
      },
      {
        question:
          "Strategi apa yang paling efektif untuk membangun dana darurat?",
        options: [
          "Menabung sisa uang bulanan",
          "Otomatisasi dengan auto debit",
          "Menabung saat ada uang lebih",
          "Menunggu bonus besar",
        ],
        correct: 1,
      },
    ],
  },
  // New categories: debt, insurance, psychology
  {
    id: 4,
    slug: "strategi-keluar-utang",
    title: "Strategi Keluar dari Utang Konsumtif",
    description:
      "Pelajari metode snowball dan avalanche untuk melunasi utang lebih cepat dan terukur.",
    category: "debt",
    duration: "14 menit",
    students: 4200,
    level: "Menengah",
    type: "article",
  image: "/illustrations/strategi-keluar-utang.svg",
    content: [
      { title: "Pemetaan Utang", text: "List semua utang: sisa pokok, bunga, jatuh tempo, denda, dan jenis (konsumtif/produktif). Transparansi adalah langkah pertama mengendalikan situasi dan menentukan prioritas intervensi." },
      { title: "Metode Snowball vs Avalanche", text: "Snowball: fokus bayar utang terkecil untuk momentum psikologis cepat. Avalanche: fokus bunga tertinggi untuk efisiensi biaya total. Pilih berdasarkan profil motivasi Anda, bukan ego." },
      { title: "Negosiasi dan Refinancing", text: "Hubungi kreditur untuk restrukturisasi: perpanjangan tenor, penurunan bunga, atau konsolidasi. Siapkan data arus kas agar proposal kredibel." },
      { title: "Disiplin Eksekusi", text: "Otomatisasi pembayaran minimum + ekstra pembayaran terjadwal. Arahkan windfall (bonus/THR) langsung ke utang prioritas sebelum sempat terpakai konsumsi." },
      { title: "Studi Kasus", text: "Dari 5 utang, Rafi pilih snowball, melunasi 2 utang kecil dalam 3 bulan sehingga free cashflow naik Rp600rb/bln, kemudian switch ke avalanche untuk menekan bunga kartu kredit tinggi." },
      { title: "Rencana Aksi 60 Hari", text: "Minggu 1: Inventaris & urutkan. Minggu 2: Pilih strategi. Minggu 3-8: Eksekusi + tracking weekly. Minggu 9: Review, pertimbangkan negosiasi jika DSR masih >40%." },
    ],
    quiz: [
      { question: "Fokus utama metode avalanche?", options: ["Utang paling kecil", "Utang bunga tertinggi", "Utang jatuh tempo terdekat", "Utang tanpa jaminan"], correct: 1 },
      { question: "Langkah pertama mengatasi utang?", options: ["Ambil utang baru", "List seluruh utang", "Abaikan penagihan", "Jual semua aset"], correct: 1 },
      { question: "Windfall sebaiknya?", options: ["Dipakai liburan", "Untuk lifestyle baru", "Untuk percepat pelunasan", "Ditukar aset berisiko"], correct: 2 },
      { question: "Kenapa catatan arus kas penting saat negosiasi?", options: ["Menambah bunga", "Membuat kreditur paham kemampuan bayar", "Mengurangi tenor", "Mengganti jenis utang"], correct: 1 },
      { question: "Kapan switch strategi dari snowball ke avalanche bisa efektif?", options: ["Saat dua utang kecil lunas dan motivasi stabil", "Saat utang pertama belum lunas", "Tidak pernah", "Hanya jika bunga 0%"], correct: 0 },
    ],
  },
  {
    id: 5,
    slug: "memahami-skor-kredit",
    title: "Memahami Skor Kredit dan Dampaknya",
    description:
      "Kenali faktor penentu skor kredit dan cara meningkatkannya secara berkelanjutan.",
    category: "debt",
    duration: "10 menit",
    students: 3100,
    level: "Pemula",
    type: "article",
  image: "/illustrations/memahami-skor-kredit.svg",
    content: [
      { title: "Apa itu Skor Kredit", text: "Representasi probabilitas gagal bayar dalam horizon tertentu. Digunakan bank untuk menilai kelayakan dan menentukan bunga." },
      { title: "Faktor Utama", text: "Riwayat pembayaran (terbesar), rasio pemanfaatan kredit (utilization), panjang histori, variasi tipe kredit, & enquiry baru." },
      { title: "Kesalahan Umum", text: "Telat bayar beberapa hari berulang, menutup akun lama sehingga umur rata-rata turun, memaksimalkan limit kartu (utilization >80%)." },
      { title: "Strategi Perbaikan", text: "Bayar tagihan autopay, turunkan utilization <30% (ideal <10% pelaporan), tambah limit hanya untuk turunkan rasio, hindari banyak aplikasi baru sekaligus." },
      { title: "Monitoring", text: "Cek laporan berkala untuk dispute kesalahan. Simpan bukti pelunasan & pastikan update tercermin setelah 1-2 siklus." },
      { title: "Rencana Aksi 3 Bulan", text: "Bulan 1: Autopay & turunkan utilization. Bulan 2: Konsisten on-time, hentikan aplikasi baru. Bulan 3: Review skor & siapkan peningkatan limit strategis jika perlu." },
    ],
    quiz: [
      { question: "Utilization ideal?", options: [">80%", "50-70%", "<30%", "<5% wajib"], correct: 2 },
      { question: "Dampak menutup kartu lama?", options: ["Umur histori turun", "Skor naik langsung", "Utilization naik otomatis", "Tidak ada efek"], correct: 0 },
      { question: "Langkah tercepat turunkan utilization?", options: ["Tambah belanja", "Bayar sebagian sebelum tanggal cetak", "Tutup kartu aktif", "Tambah aplikasi kartu baru serentak"], correct: 1 },
      { question: "Enquiry keras (hard inquiry) terlalu sering?", options: ["Tidak berpengaruh", "Bisa turunkan skor sementara", "Naikkan limit otomatis", "Hapus histori"], correct: 1 },
      { question: "Mengapa autopay penting?", options: ["Agar bisa telat", "Menjamin pembayaran tepat waktu", "Naikkan bunga", "Kurangi limit"], correct: 1 },
    ],
  },
  {
    id: 6,
    slug: "asuransi-dasar-yang-diperlukan",
    title: "Asuransi Dasar yang Wajib Dipahami",
    description:
      "Bedakan jenis asuransi inti: kesehatan, jiwa term, kendaraan, dan properti.",
    category: "insurance",
    duration: "13 menit",
    students: 2950,
    level: "Pemula",
    type: "article",
  image: "/illustrations/asuransi-dasar-yang-diperlukan.svg",
    content: [
      { title: "Fungsi Asuransi", text: "Memindahkan potensi kerugian besar (low frequency, high severity) menjadi pembayaran premi kecil yang terukur." },
      { title: "Prioritas Pembelian", text: "Urutan umum: kesehatan, jiwa term (jika ada tanggungan), baru kendaraan/properti. Fokus pada proteksi income & biaya kesehatan tinggi." },
      { title: "Evaluasi Polis", text: "Cek limit tahunan, inner limit, masa tunggu, pengecualian, rasio klaim perusahaan, dan network provider." },
      { title: "Kesalahan Umum", text: "Over insured (limit jauh melebihi kebutuhan), under insured (limit terlalu kecil), membeli produk campuran berbiaya tinggi tanpa paham struktur biaya." },
      { title: "Studi Kasus", text: "Indah memilih polis hospital plan dengan limit rendah & inner limit ketat sehingga klaim besar ditolak sebagian—menunjukkan pentingnya membaca rincian limit." },
      { title: "Rencana Evaluasi Tahunan", text: "Bandingkan kenaikan premi vs inflasi medis, cek perubahan kebutuhan (pernikahan, anak), dan menyesuaikan gap proteksi." },
    ],
    quiz: [
      { question: "Asuransi prioritas pertama?", options: ["Kendaraan", "Kesehatan", "Properti", "Perjalanan"], correct: 1 },
      { question: "Tujuan utama asuransi?", options: ["Cari keuntungan", "Transfer risiko besar", "Menabung bunga tinggi", "Diversifikasi saham"], correct: 1 },
      { question: "Inner limit adalah?", options: ["Batas per item/jenis perawatan", "Diskon premi", "Bonus investasi", "Jenis rider"], correct: 0 },
      { question: "Under insured berarti?", options: ["Proteksi cukup", "Limit terlalu kecil", "Limit terlalu besar", "Tidak punya rider"], correct: 1 },
      { question: "Evaluasi polis dilakukan?", options: ["Setiap minggu", "Saat ada perubahan hidup signifikan", "Tidak pernah", "Hanya saat klaim ditolak"], correct: 1 },
    ],
  },
  {
    id: 7,
    slug: "memilih-polis-jiwa-term",
    title: "Memilih Polis Asuransi Jiwa Term Efektif",
    description:
      "Hitung kebutuhan proteksi jiwa berbasis income replacement dan kewajiban finansial.",
    category: "insurance",
    duration: "11 menit",
    students: 2100,
    level: "Menengah",
    type: "article",
  image: "/illustrations/memilih-polis-jiwa-term.svg",
    content: [
      { title: "Menghitung Kebutuhan", text: "(Pengeluaran tahunan x tahun perlindungan) + sisa utang + biaya pendidikan anak + target finansial lain yang ingin dipastikan tercapai." },
      { title: "Term vs Whole", text: "Term: biaya rendah, fokus proteksi; Whole/Unit-linked: ada unsur investasi tapi biaya & kompleksitas tinggi—pemahaman wajib sebelum membeli." },
      { title: "Rider", text: "Critical illness, waiver of premium, accidental death—ambil hanya yang punya probabilitas & dampak relevan pada situasi keluarga." },
      { title: "Revisi Berkala", text: "Tinjau polis saat perubahan besar (kelahiran anak, pembelian rumah, kenaikan income) untuk mencegah gap proteksi." },
      { title: "Studi Kasus", text: "Tanpa review, kebutuhan proteksi Andi naik 60% setelah anak kedua namun polis tetap—keluarga berisiko underfunded jika terjadi musibah." },
      { title: "Checklist Pembelian", text: "Jelas tujuan proteksi, hitung kebutuhan, bandingkan 2-3 penawaran, cek klausa pengecualian, pastikan kemampuan bayar premi jangka panjang." },
    ],
    quiz: [
      { question: "Keunggulan term life?", options: ["Murah & fokus proteksi", "Return investasi tinggi", "Tanpa masa berlaku", "Tidak perlu underwriting"], correct: 0 },
      { question: "Kapan review polis?", options: ["Setiap minggu", "Saat perubahan finansial besar", "Tidak perlu", "Saat harga emas naik"], correct: 1 },
      { question: "Komponen utama perhitungan kebutuhan?", options: ["Pengeluaran tahunan & kewajiban", "Harga emas", "Kenaikan gaji", "Tarif pajak"], correct: 0 },
      { question: "Mengambil rider terlalu banyak berisiko?", options: ["Biaya premi membengkak", "Proteksi naik gratis", "Klaim otomatis ditolak", "Mengurangi uang pertanggungan"], correct: 0 },
      { question: "Undercoverage terjadi ketika?", options: ["Proteksi > kebutuhan", "Proteksi < kebutuhan", "Proteksi = kebutuhan", "Tidak punya rider"], correct: 1 },
    ],
  },
  {
    id: 8,
    slug: "psikologi-keputusan-keuangan",
    title: "Psikologi dalam Keputusan Keuangan",
    description:
      "Kenali bias kognitif yang mempengaruhi pilihan finansial dan cara menetralkannya.",
    category: "psychology",
    duration: "16 menit",
    students: 3300,
    level: "Menengah",
    type: "article",
  image: "/illustrations/psikologi-keputusan-keuangan.svg",
    content: [
      { title: "Anchoring", text: "Menempel pada angka awal (harga beli) sehingga menilai harga saat ini tidak objektif bahkan ketika fundamental berubah." },
      { title: "Loss Aversion", text: "Rasa sakit kehilangan lebih besar dari rasa senang keuntungan sama besar—menyebabkan menahan aset buruk & profit taking terlalu cepat." },
      { title: "Overconfidence", text: "Keyakinan berlebih atas kemampuan prediksi → ukuran posisi berlebihan, kurang diversifikasi." },
      { title: "Bias Lain", text: "Confirmation bias, herd behavior, recency bias memperkeruh penilaian risiko." },
      { title: "Mitigasi", text: "Checklist objektif, jurnal keputusan (entry, alasan, ekspektasi), aturan otomatis stop loss / rebalancing membantu menurunkan bias emosional." },
      { title: "Ritual Review", text: "Sesi bulanan mengevaluasi apakah hasil buruk karena proses salah atau varians pasar. Fokus perbaikan proses, bukan menebak harga." },
    ],
    quiz: [
      { question: "Contoh loss aversion?", options: ["Cut loss cepat", "Tahan saham turun tanpa alasan", "Diversifikasi ETF", "Rebalancing tahunan"], correct: 1 },
      { question: "Cara mitigasi bias?", options: ["Ikuti emosi", "Gunakan jurnal & checklist", "Over trade", "Hindari diversifikasi"], correct: 1 },
      { question: "Overconfidence memicu?", options: ["Ukuran posisi berlebihan", "Diversifikasi meningkat", "Biaya turun", "Risiko hilang"], correct: 0 },
      { question: "Anchoring fokus pada?", options: ["Data fundamental terkini", "Harga referensi awal", "Berita terbaru", "Rasio valuasi"], correct: 1 },
      { question: "Tujuan review berkala?", options: ["Menebak harga jangka pendek", "Evaluasi proses & bias", "Menghilangkan volatilitas", "Menghapus risiko"], correct: 1 },
    ],
  },
  {
    id: 9,
    slug: "mengatasi-inflasi-gaya-hidup",
    title: "Mengatasi Inflasi Gaya Hidup",
    description:
      "Strategi menahan kenaikan pengeluaran seiring naiknya pendapatan agar tabungan tumbuh.",
    category: "psychology",
    duration: "9 menit",
    students: 2800,
    level: "Pemula",
    type: "article",
  image: "/illustrations/mengatasi-inflasi-gaya-hidup.svg",
    content: [
      { title: "Definisi", text: "Kenaikan pengeluaran mengikuti pendapatan baru secara proporsional sehingga net saving rate stagnan." },
      { title: "Pemicu", text: "Sosial media, perbandingan sosial, bonus tahunan, peer pressure, emotional spending (reward yourself)." },
      { title: "Framework", text: "Default: tingkatkan saving/investing rate dulu (mis. +5-10%), baru upgrade gaya hidup terkurasi -> conscious spending." },
      { title: "Checklist", text: "Apakah ini kebutuhan jangka panjang? Ada alternatif lebih murah? Apakah penambahan ini menurunkan waktu mencapai tujuan?" },
      { title: "Studi Kasus", text: "Gaji naik 30%, Budi mengunci 15% ke investasi otomatis dan membatasi upgrade lifestyle ke 10% sehingga net worth tumbuh lebih cepat." },
      { title: "Rencana Kontrol", text: "Tetapkan batas maksimal kategori discretionary (%), lakukan audit triwulanan dan freeze kenaikan bila tabungan turun < target." },
    ],
    quiz: [
      { question: "Lifestyle inflation?", options: ["Turun pengeluaran", "Pengeluaran stagnan", "Pengeluaran naik ikut income", "Pendapatan turun"], correct: 2 },
      { question: "Langkah awal cegah?", options: ["Tambah cicilan", "Naikkan tabungan dulu", "Belanja gadget baru", "Ambil utang konsumtif"], correct: 1 },
      { question: "Tujuan conscious spending?", options: ["Menghilangkan semua hiburan", "Menghabiskan semua kenaikan income", "Memilih upgrade bernilai tinggi", "Menolak kenaikan gaji"], correct: 2 },
      { question: "Audit triwulanan berguna untuk?", options: ["Mempercepat impuls belanja", "Menilai drift pengeluaran", "Menambah semua kategori", "Hapus limit tabungan"], correct: 1 },
      { question: "Saving rate idealnya?", options: ["Tidak berubah meski income naik", "Sedikit meningkat saat income naik", "Turun drastis", "Tidak relevan"], correct: 1 },
    ],
  },
  {
    id: 10,
    slug: "kendali-impuls-belanja",
    title: "Kendalikan Impuls Belanja",
    description:
      "Teknik praktis menunda keputusan dan memfilter belanja emosional vs rasional.",
    category: "psychology",
    duration: "8 menit",
    students: 2600,
    level: "Pemula",
    type: "article",
  image: "/illustrations/kendali-impuls-belanja.svg",
    content: [
      { title: "Pemicu Emosi", text: "Stres, bosan, merasa 'pantasan' setelah kerja keras, fear of missing out (FOMO)." },
      { title: "Aturan 24/72 Jam", text: "Tunda pembelian non-esensial (harga > threshold) selama 24-72 jam untuk mengurangi keputusan emosional." },
      { title: "Envelope Digital", text: "Pisahkan kategori discretionary (hiburan, cafe) ke 'amplop' virtual agar sisa dana terlihat jelas." },
      { title: "Evaluasi Bulanan", text: "Audit belanja impuls yang lolos, identifikasi pola (hari, emosi, trigger)." },
      { title: "Pengganti Sehat", text: "Ganti dorongan belanja dengan aktivitas alternatif: olahraga singkat, journaling, membuat daftar keinginan ditunda." },
      { title: "Rencana Interupsi", text: "Gunakan reminder visual (wallpaper tujuan finansial) & limit kartu tersendiri untuk discretionary belanja." },
    ],
    quiz: [
      { question: "Tujuan aturan 24 jam?", options: ["Percepat keputusan", "Menahan impuls", "Naikkan pengeluaran", "Hapus kebutuhan"], correct: 1 },
      { question: "Metode amplop membantu?", options: ["Hilangkan semua belanja", "Berikan visual batas dana", "Naikkan impuls", "Campur kategori"], correct: 1 },
      { question: "Langkah evaluasi bulanan?", options: ["Abaikan pola", "Identifikasi trigger & sesuaikan strategi", "Tambah impuls", "Naikkan limit tanpa kontrol"], correct: 1 },
      { question: "Pengganti sehat bertujuan?", options: ["Memicu impuls baru", "Mengalihkan dorongan belanja", "Naikkan konsumsi", "Hapus tujuan"], correct: 1 },
      { question: "Rencana interupsi termasuk?", options: ["Wallpaper tujuan finansial", "Sembunyikan tujuan", "Tambah kartu tanpa limit", "Abaikan notifikasi"], correct: 0 },
    ],
  },
  // Additional balanced articles across original categories
  {
    id: 11,
    slug: "optimasi-anggaran-lanjutan",
    title: "Optimasi Anggaran Lanjutan",
    description: "Teknik tracking granular, batching pengeluaran, dan audit kategori untuk efisiensi lanjutan.",
    category: "budgeting",
    duration: "17 menit",
    students: 1900,
    level: "Menengah",
    type: "article",
  image: "/illustrations/optimasi-anggaran-lanjutan.svg",
    content: [
      { title: "Segmentasi Kategori", text: "Pisahkan kebutuhan (fixed & penting) vs variable wants (fleksibel) untuk analitik tajam & prioritas penghematan." },
      { title: "Batching", text: "Kelompokkan belanja rutin (groceries, langganan) agar pengawasan lebih mudah dan mengurangi frekuensi impuls." },
      { title: "Review Mingguan", text: "Micro-adjust sebelum kebablasan di akhir bulan. Intervensi dini lebih murah secara psikologis." },
      { title: "Tooling", text: "Gunakan sheet pivot, kategori tag, color coding variance >10%." },
      { title: "MetriK Kunci", text: "Variance per kategori, % discretionary vs income, savings rate trend 3 bulan, kecepatan akumulasi dana tujuan." },
      { title: "Continuous Improvement", text: "Set target per bulan: turunkan variance kategori tertinggi, otomatisasi pembayaran berulang untuk mengurangi leak kognitif." },
    ],
    quiz: [
      { question: "Tujuan batching?", options: ["Tambah impuls", "Kurangi friction & frekuensi belanja", "Naikkan variance", "Hilangkan kebutuhan"], correct: 1 },
      { question: "Variance >10% perlu?", options: ["Diabaikan", "Investigasi & penyesuaian", "Diperbesar", "Dipindah ke pendapatan"], correct: 1 },
      { question: "MetriK kunci budgeting lanjutan?", options: ["Warna favorit", "Savings rate trend", "Jumlah aplikasi di HP", "Jumlah teman"], correct: 1 },
      { question: "Segmentasi kategori membantu?", options: ["Membingungkan analisa", "Fokus intervensi hemat", "Naikkan pengeluaran", "Hilangkan tabungan"], correct: 1 },
      { question: "Perbaikan berkelanjutan berarti?", options: ["Tidak ubah apa pun", "Iterasi kecil konsisten", "Sekali besar lalu berhenti", "Hapus tracking"], correct: 1 },
    ],
  },
  {
    id: 12,
    slug: "dasar-analisis-saham",
    title: "Dasar Analisis Saham",
    description: "Mengenal fundamental: EPS, PER, PBV, margin, arus kas dan konteks industri.",
    category: "investing",
    duration: "18 menit",
    students: 2500,
    level: "Menengah",
    type: "article",
  image: "/illustrations/dasar-analisis-saham.svg",
    content: [
      { title: "Rasio Utama", text: "PER, PBV, ROE, DER membantu valuasi dan menilai efisiensi modal & struktur utang." },
      { title: "Laporan Keuangan", text: "Fokus tren revenue, margin, arus kas operasi positif vs laba akuntansi." },
      { title: "Moat & Industri", text: "Keunggulan kompetitif: switching cost, brand, network effect. Perhatikan fase siklus industri (mature vs growth)." },
      { title: "Checklist", text: "Validasi: bisnis dipahami, fundamental stabil, valuasi wajar, manajemen kredibel." },
      { title: "Risiko", text: "Regulasi, disrupsi teknologi, leverage tinggi, ketergantungan pelanggan besar tunggal." },
      { title: "Studi Kasus", text: "Saham dengan ROE konsisten & arus kas operasi kuat cenderung bertahan di koreksi panjang dibanding growth tanpa profit." },
    ],
    quiz: [
      { question: "Rasio menilai leverage?", options: ["ROE", "DER", "PER", "Margin kotor"], correct: 1 },
      { question: "Moat contoh?", options: ["Network effect", "Harga diskon sementara", "Promo musiman", "Inflasi"], correct: 0 },
      { question: "Arus kas operasi negatif kronis?", options: ["Perlu ditinjau lebih lanjut", "Selalu aman", "Tanda profitabilitas tinggi", "Menghapus risiko"], correct: 0 },
      { question: "Checklist termasuk?", options: ["Bisnis dipahami", "Hanya rumor", "Tidak baca laporan", "Spekulasi murni"], correct: 0 },
      { question: "Risiko regulasi berarti?", options: ["Aturan bisa ubah profit model", "Harga selalu naik", "Kinerja dijamin", "Tidak ada dampak"], correct: 0 },
    ],
  },
  {
    id: 13,
    slug: "rencana-keuangan-lima-tahun",
    title: "Membangun Rencana Keuangan 5 Tahun",
    description: "Framework SMART, prioritas tujuan, dan review terstruktur tahunan.",
    category: "planning",
    duration: "14 menit",
    students: 1750,
    level: "Pemula",
    type: "article",
  image: "/illustrations/rencana-keuangan-lima-tahun.svg",
    content: [
      { title: "Inventaris Tujuan", text: "List tujuan kategori: proteksi (dana darurat, asuransi), likuiditas, pertumbuhan, aspirasi (travel, pendidikan lanjut)." },
      { title: "Prioritas & Timeline", text: "Skor dampak vs urgensi untuk urut eksekusi & alokasi sumber terbatas." },
      { title: "Penetapan Nominal", text: "Backward calculation dari harga masa depan (inflasi asumsi 4-5%)." },
      { title: "Review", text: "Evaluasi drift & penyesuaian tahunan atau saat perubahan besar." },
      { title: "Tracking", text: "Gunakan progress bar per tujuan; upgrade alokasi saat milestone tercapai lebih cepat." },
      { title: "Studi Kasus", text: "Tanpa prioritisasi, tabungan Rika terpecah ke 7 tujuan sehingga semua lambat; fokus top 3 mempercepat pencapaian 2 di antaranya." },
    ],
    quiz: [
      { question: "Prioritas ditentukan?", options: ["Dampak & urgensi", "Random", "Warna tujuan", "Alfabet"], correct: 0 },
      { question: "Backward calculation gunakan?", options: ["Inflasi masa depan", "Harga tahun lalu", "Bunga tabungan saja", "Nilai tukar tetap"], correct: 0 },
      { question: "Tracking membantu?", options: ["Motivasi & penyesuaian alokasi", "Menghambat tabungan", "Menambah kebingungan", "Menghapus tujuan"], correct: 0 },
      { question: "Banyak tujuan kecil sekaligus?", options: ["Selalu optimal", "Dapat melambatkan progres", "Tidak berpengaruh", "Menghapus fokus"], correct: 1 },
      { question: "Review dilakukan?", options: ["Tidak pernah", "Tahunan atau saat perubahan besar", "Setiap hari", "Saat harga emas turun"], correct: 1 },
    ],
  },
  {
    id: 14,
    slug: "negosiasi-bunga-pinjaman",
    title: "Negosiasi Bunga Pinjaman Efektif",
    description: "Taktik menurunkan beban bunga dengan perbandingan, timing, dan profil risiko sehat.",
    category: "debt",
    duration: "9 menit",
    students: 1320,
    level: "Menengah",
    type: "article",
  image: "/illustrations/negosiasi-bunga-pinjaman.svg",
    content: [
      { title: "Persiapan Dokumen", text: "Slip gaji, mutasi rekening, laporan usaha (jika wirausaha), histori bayar baik meningkatkan posisi tawar." },
      { title: "Benchmark", text: "Bandingkan minimal 3 lembaga: effective rate, biaya provisi, penalti pelunasan." },
      { title: "Timing", text: "Ajukan saat suku bunga acuan turun atau DSR Anda membaik." },
      { title: "Alternatif", text: "Refinancing, konsolidasi, top-up—evaluasi total biaya vs penghematan bunga." },
      { title: "Strategi Negosiasi", text: "Tawarkan bukti stabilitas pendapatan & histori on-time, gunakan penawaran kompetitor sebagai leverage." },
      { title: "Studi Kasus", text: "Refinancing KPR menurunkan rate 1% → hemat total bunga ratusan juta sepanjang sisa tenor." },
    ],
    quiz: [
      { question: "Benchmark penting untuk?", options: ["Tahu opsi & leverage", "Menaikkan biaya", "Menghapus negosiasi", "Menolak penawaran bagus"], correct: 0 },
      { question: "Dokumen kuat menandakan?", options: ["Risiko lebih rendah", "Risiko tinggi", "Bunga naik otomatis", "Tidak relevan"], correct: 0 },
      { question: "Refinancing dipilih jika?", options: ["Rate baru lebih tinggi", "Rate baru signifikan lebih rendah setelah biaya", "Tidak ada selisih", "Tenor lebih pendek dengan biaya tinggi"], correct: 1 },
      { question: "DSR yang membaik?", options: ["Menurunkan daya tawar", "Meningkatkan daya tawar", "Tidak pengaruh", "Hanya untuk investasi"], correct: 1 },
      { question: "Leverage negosiasi?", options: ["Penawaran kompetitor", "Menutup semua data", "Datang tanpa dokumen", "Tidak riset"], correct: 0 },
    ],
  },
  {
    id: 15,
    slug: "perlindungan-aset-kritis",
    title: "Perlindungan Aset Kritis",
    description: "Menentukan prioritas proteksi aset bernilai tinggi dan mitigasi risiko kerusakan/kehilangan.",
    category: "insurance",
    duration: "12 menit",
    students: 1470,
    level: "Menengah",
    type: "article",
  image: "/illustrations/perlindungan-aset-kritis.svg",
    content: [
      { title: "Identifikasi Aset", text: "Kelompokkan aset: produktif (menghasilkan), konsumtif, apresiatif (berpotensi naik nilai)." },
      { title: "Risiko", text: "Risiko fisik (kerusakan), legal, operasional (downtime), pasar (depresiasi)." },
      { title: "Strategi Proteksi", text: "Asuransi relevan, diversifikasi lokasi, dokumentasi & serial number, IoT monitoring untuk aset kritis." },
      { title: "Checklist Tahunan", text: "Audit nilai pasar vs pertanggungan, cek gap & penyesuaian limit." },
      { title: "Studi Kasus", text: "Tanpa update nilai, polis aset mesin pabrik under insured 40% saat klaim—kerugian besar tidak terganti." },
      { title: "Rencana Aksi", text: "Q1 daftar & klasifikasi, Q2 mitigasi gap besar, Q3 tes prosedur respon insiden, Q4 review polis & update." },
    ],
    quiz: [
      { question: "Under insured terjadi saat?", options: ["Nilai pertanggungan < nilai aset", "Nilai pertanggungan > nilai aset", "Nilai sama", "Tidak punya aset"], correct: 0 },
      { question: "IoT monitoring berguna untuk?", options: ["Pantau kondisi aset real-time", "Naikkan premi", "Menghapus aset", "Mengurangi dokumentasi"], correct: 0 },
      { question: "Audit tahunan bertujuan?", options: ["Menyesuaikan proteksi dengan nilai terkini", "Menurunkan semua limit acak", "Menghapus polis", "Tidak perlu"], correct: 0 },
      { question: "Risiko operasional?", options: ["Downtime menghambat produksi", "Perubahan warna aset", "Harga diskon", "Kenaikan premi"], correct: 0 },
      { question: "Diversifikasi lokasi?", options: ["Kurangi konsentrasi risiko", "Tambah risiko fisik", "Hapus dokumentasi", "Naikkan kerusakan"], correct: 0 },
    ],
  },
  {
    id: 16,
    slug: "mindset-investor-disiplin",
    title: "Mindset Investor Disiplin",
    description: "Bangun kerangka mental konsisten: proses > hasil jangka pendek.",
    category: "psychology",
    duration: "10 menit",
    students: 1610,
    level: "Menengah",
    type: "article",
  image: "/illustrations/mindset-investor-disiplin.svg",
    content: [
      { title: "Rule-Based", text: "Sistem entry/exit objektif menurunkan keputusan emosional & konsistensi evaluasi." },
      { title: "Jurnal", text: "Catat alasan setiap transaksi, hipotesis & kondisi pasar untuk post-mortem." },
      { title: "Evaluasi", text: "Review bulanan fokus apakah proses dipatuhi bukan sekadar hasil angka." },
      { title: "Kebiasaan", text: "Kurangi noise: batasi cek harga berlebihan, gunakan waktu terjadwal." },
      { title: "MetriK Perilaku", text: "% transaksi sesuai aturan, waktu rata-rata menahan posisi, jumlah deviasi yang dibenarkan tertulis." },
      { title: "Studi Kasus", text: "Investor disiplin dengan 85% kepatuhan rule outperform rekan impulsif walau win rate serupa." },
    ],
    quiz: [
      { question: "Tujuan jurnal?", options: ["Emosi bebas", "Dokumentasi untuk evaluasi", "Tambah impuls", "Hilangkan aturan"], correct: 1 },
      { question: "% kepatuhan rule?", options: ["MetriK perilaku", "Spread bid-ask", "Harga emas", "Inflasi global"], correct: 0 },
      { question: "Evaluasi fokus?", options: ["Hasil jangka pendek saja", "Kepatuhan proses", "Rumor pasar", "Warna grafik"], correct: 1 },
      { question: "Batasi cek harga untuk?", options: ["Kurangi noise emosional", "Naikkan stres", "Tambah impuls", "Hilangkan disiplin"], correct: 0 },
      { question: "Studi kasus tunjukkan?", options: ["Disiplin proses penting", "Impuls selalu menang", "Rule tidak relevan", "Jurnal menghambat"], correct: 0 },
    ],
  },
  {
    id: 17,
    slug: "alokasi-aset-dasar",
    title: "Alokasi Aset Dasar",
    description: "Membagi portofolio lintas kelas aset sesuai profil risiko dan horizon waktu.",
    category: "investing",
    duration: "15 menit",
    students: 1880,
    level: "Pemula",
    type: "article",
  image: "/illustrations/alokasi-aset-dasar.svg",
    content: [
      { title: "Tujuan & Horizon", text: "Short vs long term mempengaruhi proporsi kas/obligasi/saham & alternatif." },
      { title: "Profil Risiko", text: "Toleransi volatilitas menentukan eksposur aset agresif—ukur dengan kuisioner & pengalaman sebelumnya." },
      { title: "Model Alokasi", text: "60/40 klasik, glide path (turun risiko mendekati target), core-satellite (indeks inti + posisi taktis)." },
      { title: "Penyesuaian", text: "Rebalancing & lifecycle shifting menjaga profil sesuai rencana." },
      { title: "MetriK", text: "Tracking deviasi alokasi > toleransi (mis. ±5%), volatility portofolio, drawdown maksimum." },
      { title: "Studi Kasus", text: "Tanpa rebalancing, saham overweight saat crash → drawdown lebih dalam dibanding portofolio disiplin." },
    ],
    quiz: [
      { question: "Tujuan rebalancing?", options: ["Menjaga alokasi target", "Mengejar harga naik", "Hindari diversifikasi", "Naikkan risiko tak terkendali"], correct: 0 },
      { question: "Core-satellite terdiri dari?", options: ["Satu saham saja", "Inti indeks + posisi taktis", "Hanya kas", "Hanya obligasi"], correct: 1 },
      { question: "Deviasi alokasi besar?", options: ["Tidak penting", "Perlu aksi rebalancing", "Selalu dibiarkan", "Hilangkan aset"], correct: 1 },
      { question: "Glide path?", options: ["Naikkan risiko saat mendekati tujuan", "Turunkan risiko mendekati tujuan", "Tanpa perubahan", "Hapus aset pendapatan tetap"], correct: 1 },
      { question: "Drawdown maksimum mengukur?", options: ["Penurunan puncak ke lembah terburuk", "Return tahunan rata-rata", "Dividen", "Biaya broker"], correct: 0 },
    ],
  },
  {
    id: 18,
    slug: "roadmap-tabungan-tujuan",
    title: "Roadmap Tabungan Tujuan Spesifik",
    description: "Membuat bucket: darurat, pendidikan, perjalanan, DP rumah dengan auto-funding.",
    category: "planning",
    duration: "11 menit",
    students: 1760,
    level: "Pemula",
    type: "article",
  image: "/illustrations/roadmap-tabungan-tujuan.svg",
    content: [
      { title: "Kategorisasi Bucket", text: "Pisahkan akun/virtual account per tujuan: darurat, pendidikan, perjalanan, DP rumah." },
      { title: "Auto Transfer", text: "Sinkron dengan tanggal gajian untuk menghindari konsumsi sebelum dialokasikan." },
      { title: "Prioritas Dinamis", text: "Adjust alokasi saat income variabel naik/turun atau tujuan tercapai cepat." },
      { title: "Pelacakan", text: "Visual progress bar & persentase forecast waktu tercapai." },
      { title: "Studi Kasus", text: "Dengan bucket terpisah, kebocoran dana liburan ke pengeluaran harian menurun drastis." },
      { title: "Rencana Kuartalan", text: "Setiap kuartal review target & inflasi, sesuaikan nominal bulanan." },
    ],
    quiz: [
      { question: "Tujuan bucket?", options: ["Mencampur semua dana", "Alokasi jelas per tujuan", "Menurunkan visibilitas", "Menghapus prioritas"], correct: 1 },
      { question: "Auto transfer mencegah?", options: ["Kebocoran sebelum tabung", "Kenaikan tabungan", "Perencanaan", "Review"], correct: 0 },
      { question: "Prioritas dinamis artinya?", options: ["Tidak pernah berubah", "Menyesuaikan alokasi saat kondisi berubah", "Hapus tujuan", "Selalu tambah semua"], correct: 1 },
      { question: "Progress bar membantu?", options: ["Motivasi & monitoring", "Menghambat tabungan", "Menambah kebingungan", "Menutup catatan"], correct: 0 },
      { question: "Review kuartalan untuk?", options: ["Sesuaikan inflasi & target", "Menambah impuls", "Hapus bucket", "Turunkan visibilitas"], correct: 0 },
    ],
  },
  {
    id: 19,
    slug: "restrukturisasi-utang-tepat",
    title: "Restrukturisasi Utang yang Tepat",
    description: "Menilai kapan refinancing, konsolidasi, atau negosiasi lebih menguntungkan.",
    category: "debt",
    duration: "13 menit",
    students: 1210,
    level: "Menengah",
    type: "article",
  image: "/illustrations/restrukturisasi-utang-tepat.svg",
    content: [
      { title: "Indikator Perlu Restruktur", text: "DSR tinggi, arus kas negatif, bunga variabel meningkat signifikan, sering telat bayar." },
      { title: "Opsi", text: "Konsolidasi, top-up, refinancing, negosiasi bunga, grace period sementara." },
      { title: "Analisa Biaya", text: "Bandingkan biaya admin, penalti, vs penghematan bunga masa depan (NPV)." },
      { title: "Risiko", text: "Tenor diperpanjang menurunkan cicilan tapi total bunga naik; disiplin tambahan diperlukan." },
      { title: "Studi Kasus", text: "Refinancing kartu kredit ke pinjaman bunga lebih rendah turunkan cicilan 35% dan percepat pelunasan 6 bulan." },
      { title: "Rencana Monitoring", text: "Cek DSR bulanan, targetkan <35% pasca restruktur; simpan dokumen perjanjian baru." },
    ],
    quiz: [
      { question: "Restruktur dipertimbangkan saat?", options: ["DSR normal", "DSR tinggi & arus kas negatif", "Bunga turun", "Tidak ada utang"], correct: 1 },
      { question: "Risiko perpanjang tenor?", options: ["Total bunga naik", "Total bunga turun pasti", "Tidak ada perubahan", "Utang hilang"], correct: 0 },
      { question: "Analisa biaya fokus?", options: ["Admin vs penghematan bunga", "Warna kartu", "Jumlah rekening", "Lokasi bank"], correct: 0 },
      { question: "Konsolidasi berarti?", options: ["Gabung beberapa utang jadi satu", "Tambah utang baru acak", "Hapus histori", "Naikkan bunga tanpa alasan"], correct: 0 },
      { question: "Monitoring pasca restruktur?", options: ["Cek DSR & kepatuhan bayar", "Abaikan cicilan", "Tambah hutang baru", "Tidak perlu dokumen"], correct: 0 },
    ],
  },
  {
    id: 20,
    slug: "analisis-klaim-asuransi",
    title: "Analisis Klaim Asuransi Efektif",
    description: "Langkah dokumentasi dan eskalasi agar klaim tidak ditolak sia-sia.",
    category: "insurance",
    duration: "9 menit",
    students: 1290,
    level: "Menengah",
    type: "article",
  image: "/illustrations/analisis-klaim-asuransi.svg",
    content: [
      { title: "Pra-Klaim", text: "Pahami pengecualian, masa tunggu, prosedur provider network vs reimbursement." },
      { title: "Dokumentasi", text: "Kelengkapan bukti, kronologi tertulis, foto/scan dokumen utama." },
      { title: "Eskalasi", text: "Banding resmi dengan tambahan bukti & referensi klausul polis." },
      { title: "Pencegahan", text: "Update data polis berkala (alamat, status tanggungan) untuk hindari dispute." },
      { title: "Studi Kasus", text: "Klaim ditolak karena masa tunggu belum lewat—menegaskan pentingnya pemahaman inception date." },
      { title: "Checklist Klaim", text: "1. Polis aktif 2. Masa tunggu selesai 3. Dokumen lengkap 4. Form klaim benar 5. Bukti pembayaran." },
    ],
    quiz: [
      { question: "Masa tunggu berarti?", options: ["Periode sebelum manfaat berlaku", "Diskon premi", "Bonus investasi", "Periode klaim ganda"], correct: 0 },
      { question: "Klaim ditolak sering karena?", options: ["Dokumen tidak lengkap", "Dokumen terlalu lengkap", "Premi kelebihan", "Tidak ada kronologi"], correct: 0 },
      { question: "Banding efektif?", options: ["Tanpa bukti", "Dengan tambahan bukti & referensi polis", "Marah di CS", "Diam saja"], correct: 1 },
      { question: "Update data polis penting agar?", options: ["Mengurangi dispute", "Menaikkan pengeluaran acak", "Menghapus manfaat", "Hilangkan tanggungan"], correct: 0 },
      { question: "Checklist klaim termasuk?", options: ["Polis aktif & dokumen lengkap", "Hanya tanda tangan", "Tanpa formulir", "Tanpa bukti"], correct: 0 },
    ],
  },
  {
    id: 21,
    slug: "framework-keputusan-rational",
    title: "Framework Keputusan Rasional",
    description: "Gunakan struktur objektif untuk mengurangi bias dan menilai opsi finansial.",
    category: "psychology",
    duration: "12 menit",
    students: 1410,
    level: "Menengah",
    type: "article",
  image: "/illustrations/framework-keputusan-rational.svg",
    content: [
      { title: "Definisi Masalah", text: "Harus spesifik, terukur, batasan jelas untuk menghindari solusi kabur." },
      { title: "Alternatif", text: "List opsi + konsekuensi, termasuk opsi 'do nothing'." },
      { title: "Skoring", text: "Bobot kriteria (risiko, ROI, waktu) lalu nilai tiap opsi untuk objektivitas." },
      { title: "Review", text: "Evaluasi hasil vs ekspektasi & perbaiki model keputusan." },
      { title: "Bias Reduction", text: "Pisahkan fase ide vs evaluasi, gunakan data historis bukan asumsi emosional." },
      { title: "Studi Kasus", text: "Dengan kerangka scoring, pilihan investasi UMKM emosional dialihkan ke opsi lebih terukur dengan ROI lebih tinggi." },
    ],
    quiz: [
      { question: "Masalah harus?", options: ["Kabur", "Spesifik & terukur", "Tanpa batasan", "Selalu emosional"], correct: 1 },
      { question: "Skoring bertujuan?", options: ["Objektivitas keputusan", "Tambah bias", "Singkirkan data", "Acak pilihan"], correct: 0 },
      { question: "Alternatif 'do nothing'?", options: ["Tidak valid", "Harus dipertimbangkan", "Selalu dipilih", "Menghapus opsi lain"], correct: 1 },
      { question: "Bias reduction salah satu cara?", options: ["Campur ide & evaluasi", "Pisahkan fase", "Abaikan data", "Ikuti emosi"], correct: 1 },
      { question: "Review akhir?", options: ["Perbaiki model keputusan", "Hapus pelajaran", "Abaikan hasil", "Ganti semua data"], correct: 0 },
    ],
  },
  {
    id: 22,
    slug: "diversifikasi-multi-aset",
    title: "Diversifikasi Multi Aset Modern",
    description: "Memadukan aset tradisional & alternatif untuk profil risiko seimbang.",
    category: "investing",
    duration: "17 menit",
    students: 1580,
    level: "Lanjutan",
    type: "article",
  image: "/illustrations/diversifikasi-multi-aset.svg",
    content: [
      { title: "Korelasi", text: "Gunakan aset korelasi rendah untuk stabilkan volatilitas portofolio total." },
      { title: "Alternatif", text: "REIT, komoditas, private credit, peer lending, infrastruktur." },
      { title: "Bobot Dinamis", text: "Adjust berdasarkan regime pasar (inflasi tinggi, resesi) dengan batas disiplin." },
      { title: "Risiko Baru", text: "Likuiditas rendah, valuasi tidak transparan, biaya tinggi." },
      { title: "MetriK", text: "Sharpe ratio, drawdown, korelasi rolling 12 bulan, kontribusi risiko (risk parity)." },
      { title: "Studi Kasus", text: "Menambah komoditas saat inflasi tinggi menurunkan drawdown ekuitas keseluruhan." },
    ],
    quiz: [
      { question: "Aset korelasi rendah?", options: ["Kurangi volatilitas portofolio", "Naikkan korelasi", "Hapus diversifikasi", "Tambah risiko tak terkendali"], correct: 0 },
      { question: "Contoh aset alternatif?", options: ["REIT", "Tabungan biasa", "Kas rumah", "Listrik"], correct: 0 },
      { question: "Risiko private asset?", options: ["Likuiditas rendah", "Likuiditas tinggi", "Transparansi penuh", "Tanpa biaya"], correct: 0 },
      { question: "MetriK risk-adjusted?", options: ["Sharpe ratio", "Berat kertas", "Warna logo", "Nomor rekening"], correct: 0 },
      { question: "Bobot dinamis berarti?", options: ["Sesuaikan eksposur sesuai regime pasar", "Acak alokasi", "Tidak pernah ubah", "Hapus diversifikasi"], correct: 0 },
    ],
  },
  {
    id: 23,
    slug: "arsitektur-tujuan-keuangan",
    title: "Arsitektur Tujuan Keuangan Holistik",
    description: "Layering tujuan mikro-makro agar alokasi sumber daya efisien.",
    category: "planning",
    duration: "16 menit",
    students: 1490,
    level: "Lanjutan",
    type: "article",
  image: "/illustrations/arsitektur-tujuan-keuangan.svg",
    content: [
      { title: "Struktur", text: "Hierarki: fondasi (darurat, proteksi), pertumbuhan (investasi), aspirasi (gaya hidup, impian)." },
      { title: "Mapping Cashflow", text: "Alokasikan arus masuk ke bucket prioritas sebelum konsumsi variabel." },
      { title: "Trade-Off", text: "Evaluasi opportunity cost setiap tambahan pengeluaran aspiratif." },
      { title: "Adaptasi", text: "Iterasi saat asumsi (income, inflasi, tujuan) berubah untuk menjaga relevansi." },
      { title: "Integrasi Jangka Pendek & Panjang", text: "Pastikan tujuan mikro mendukung makro; hindari konflik alokasi." },
      { title: "Studi Kasus", text: "Tanpa arsitektur, dana tersebar acak; setelah struktur, pencapaian tujuan rumah dipercepat 1 tahun." },
    ],
    quiz: [
      { question: "Hierarki awal fokus?", options: ["Fondasi", "Aspirasi", "Semua sekaligus acak", "Tidak perlu"], correct: 0 },
      { question: "Mapping cashflow berarti?", options: ["Alokasi terencana ke tujuan", "Belanja acak", "Menunda semua tujuan", "Hapus tabungan"], correct: 0 },
      { question: "Trade-off evaluasi?", options: ["Opportunity cost", "Warna kartu", "Ukuran dompet", "Jumlah aplikasi"], correct: 0 },
      { question: "Adaptasi dilakukan saat?", options: ["Asumsi berubah", "Tidak pernah", "Setiap jam", "Saat bosan"], correct: 0 },
      { question: "Integrasi mikro-makro mencegah?", options: ["Konflik alokasi", "Konsistensi", "Tujuan tercapai", "Prioritas jelas"], correct: 0 },
    ],
  },
];

export function getArticleBySlug(slug: string) {
  return articleModules.find((m) => m.slug === slug);
}
